### ISSUE TITLE
Dockervolume /data

### ISSUE THREAD

**Issue by fabiankuffer** [Cryp-Tour/server#92]
In der Docker Compose Datei ist das Volume: /home/gh-deploy/cryptour-backend:/data:ro auf Readonly gesetzt. Deswegen können keine GPX-Dateien und Bilder hochgeladen werden.

Hat es einen bestimmten Grund, wieso es als Readonly gesetzt ist?

**Comment by daullmer** [comment]
Nö, hat keinen Grund. Hab wahrscheinlich beim Erstellen einfach vergessen, dass man Bilder und GPX hochladen muss 🥴
Hab's geändert
